title: Add a Rigidbody component
hero_image: images/banner.png
description: Add a Rigidbody component
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Add a Rigidbody component
